apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: bXl1c2Vy           # Base64 encoded 'myuser'
  mongo-password: bXlwYXNzd29yZA==  # Base64 encoded 'mypassword'
