apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonmongoapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonmongoapp
  template:
    metadata:
      labels:
        app: pythonmongoapp
    spec:
      containers:
      - name: pythonmongoapp
        image: akimov1/pythonmongoapp
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_HOST
          value: mongodb-service
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_DB
          value: "mydatabase"
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
