apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    app: pythonmongoapp
  ports:
  - protocol: TCP
    port: 80          # Service port
    targetPort: 5000  # Container port
    nodePort: 30080   # Node port (choose a port between 30000-32767)
